---
- name: Create portal directories
  file:
    path={{ item }}
    state=directory
    owner={{ provision__admin_user }} group={{ common_web_user }} mode=775 
    recurse=true
  with_items:
    - "{{ portal__docroot }}"
    - "{{ portal__redirects }}"
    
- name: Deploy subsite redirect instructions
  template:
    src=nginx_portal_redirect.j2
    dest={{ portal__redirects }}/{{ item.name }}
    owner=root group={{ common_web_user }} mode=0640
  with_items: portal__subsites
  notify: reload nginx
