---
dependencies:
  - portal
  - role: datasync_rsync
    datasync_rsync__data_dirs: 
      - name: "wikipedia_for_schools"
        remote_host: "{{ provision__rachel_mirror_host }}"
        remote_dir: "{{ provision__rachel_mirror_name }}/wikipedia_for_schools/"
        local_dir: "{{ portal__modules_dir }}/wikipedia_for_schools"
        
