---
#- debug: var={{web_server__vhosts}}

- name: Deploy vhosts
  template: 
    src=vhost.conf
    dest={{ nginx__sites_dir }}/{{ item.name }}.conf
    owner=root group={{ common_web_user }} mode=0644
  with_items: web_server__vhosts
  notify: restart nginx
  
- name: Default vhost specified. Remove nginx default.
  file:
    name={{ nginx__sites_dir }}/default
    state=absent
  when: >
    web_server__default_vhost is defined
  notify: restart nginx
