---
- name: Install rsync
  apt: name=rsync state=present

- name: Create data folders
  file:
    path={{ item.local_dir }}
    owner={{ item.owner|default(datasync_rsync__dir_defaults.owner) }}
    group={{ item.group|default(datasync_rsync__dir_defaults.group) }}
    mode={{ item.permissions|default(datasync_rsync__dir_defaults.permissions) }}
    state=directory
  with_items: datasync_rsync__data_dirs

- name: Install sync scripts
  template:
    src=syncscript.sh.j2
    dest={{ datasync_rsync__sync_scripts_dir }}/{{ item.name }}
    owner=root group=root mode=0554
  with_items: datasync_rsync__data_dirs

- name: Run sync scripts
  shell: "{{ datasync_rsync__sync_scripts_dir }}/{{ item.name }}&"
  with_items: datasync_rsync__data_dirs
  ignore_errors: true
  when: >
    (item.auto_sync is defined and item.auto_sync) or
    (item.auto_sync is not defined and cron_datasync__auto_sync)
  
