---
# Teacher account (password 'Tunapanda2')
- user: name={{ users__admin_user }} shell=/bin/bash password='$6$rounds=100000$n/tP8Zo.SDVWsI2V$W.tfpo74.ZzmdO1Uv6cXvqn.v31YgheQT1ACbwWXRot2p2HJ8AXk/voPpphHEXymMohwKpf6PFihEdc7uKgsR/'
  when: user__reset_admin_password
- name: configure sudoers
  lineinfile: dest=/etc/sudoers backup=yes state=present regexp='^{{ users__admin_user }}' line='{{ users__admin_user }} ALL=(ALL) {{ "" if users__sudo_require_password else "NOPASSWD:ALL" }}'

## TODO: Only do this if user doesn't exist!!
# Student accounts (password 'changeme')
- user: name={{ item }} shell=/bin/bash password='$6$rounds=100000$1NOGcsJFKk8qXjLZ$JYXYslwfXejJbrAu2apTVvcjRXtdKveICJgw3UxAMaGlxx.1SrH5QAiQgzkL9wDuFTBfdUq9YWL6S3ew8zhzw/'
  with_sequence: start=1 end={{ users__num_students }} format=student%02d
  when: users__num_students > 0
- command: chage -d0 {{ item }}
  with_sequence: start=1 end={{ users__num_students }} format=student%02d
  when: users__num_students > 0
  when: users__force_student_pw_change

