---
sphider__root: "{{ provision__data_dir }}/rsphider"
sphider__urlpath: "/rsphider"
sphider__db_name: "sphider_plus"
sphider__db_user: "rsphider"
sphider__db_pass: "rsphider"
#sphider__root: "{{ provision__data_dir }}/sphider"
