---
#
# TODO: May want to replace this home-grown role with something like this...
# http://wiki.gema-soft.de/doku.php?id=it-administration:tools:ansible:ferm
#
- name: Ensure iptables is installed (debian)
  apt: pkg={{ item }} state=installed
  with_items:
    - iptables
    - conntrack
    - psmisc

- name: Create iptables rules dir
  file:
    state=directory
    dest="{{ iptables__base_dir }}/rules.d"
    mode="0755"

- name: Set up iptables 
  template:
    src={{ item }}
    dest="{{ iptables__base_dir }}/"
    mode="0744"
  with_items:
    - clear.sh
    - load.sh
  notify:
    - reload iptables

- name: Set up iptables init script
  template: src=iptables_init_script.j2 dest=/etc/init.d/iptables owner=root group=root mode=751

- name: Load iptables automatically
  service:
    name=iptables
    enabled=true

