---
## Sphider Setup ##
# Since we're going to make local changes, don't auto-update
# TODO: maybe add lines to .git/info/exclude to ignore files
# we plan to change?
- name: Clone sphider repo
  git: >
    repo=https://github.com/tunapanda/rsphider
    dest={{ sphider__root }}
    update=no
    
- name: Set base perms on docroot
  file:
    dest="{{sphider__root}}"
    owner={{ provision__admin_user }} group={{ common_web_user }} mode=775
    
- name: Set special perms on docroot subdirectories
  file:
     path={{ sphider__root }}/{{ item }}
     owner={{ provision__admin_user }}
     group={{ common_web_user }}
     mode=4775
     recurse=true
     state=directory
  with_items:
     - admin
     - settings
     - include/IDS/tmp

- name: Install MySQL packages
  apt:
    name={{ item }}
    state=installed
  with_items:
    - python-mysqldb
    - mysql-server
    - php5-mysql
    - php5-cli
    
- name: Start MySQL server
  service:
    name=mysql
    state=started

- name: Create rsphider database
  mysql_db:
    name={{ sphider__db_name }}
    state=present
  register: db_create

- name: Create rsphider db user
  mysql_user:
    'name={{ sphider__db_user }}
    password={{ sphider__db_pass }}
    state=present
    priv={{ sphider__db_name }}.*:ALL'

- name: Configure rsphider
  lineinfile: >
    dest='{{ sphider__root }}/settings/database.php'
    regexp='^\${{ item.var }}.*'
    line='${{ item.var }} = "{{ item.val }}";'
    backrefs=true
  with_items:
    - var: "mysql_user1"
      val: "{{ sphider__db_user }}"
    - var: "mysql_password1"
      val: "{{ sphider__db_pass }}"
  
- name: Populate rsphider database
  shell: >
    echo "" | 
    php5 -R 'include("install_tables.php");' 
    -B 'parse_str($argv[1], $_GET);' 'f=1&db_num=0'
  args:
    chdir: "{{ sphider__root }}/admin/"
  when: db_create.changed


  

      
