---
- name: Deploy dnsmasq dns config
  template:
    src=dnsmasq/01-dns.conf
    dest={{ dnsmasq__dir }}/01-dns.conf
  notify: reload dnsmasq
    
- name: set up /etc/hosts entry
  lineinfile: 
    dest="/etc/hosts"
    regexp="^\d+\.\d+\.\d+\.\d+\s+{{provision__fqdn}}$"
    line="{{ provision__internal_interface.ipv4.address }} {{ provision__fqdn }}"
    state=present
