---
dependencies:
  - mail_server
  - role: web_server_vhosts
    web_server__vhosts:
      - name: learninglocker
        docroot: "{{learninglocker__root}}/public"
        alt_404: "/index.php?$query_string"
