---
- name: Install nginx
  apt:
    name={{item}}
    state=installed
  with_items:
    - nginx
    - php5-fpm

- name: Disable Apache
  service:
    name=apache2
    state=stopped
    enabled=false
  ignore_errors: yes
     
- name: PHP FPM should be running
  service:
    name=php5-fpm
    state=started
    
- name: Configure nginx
  template:
    src=nginx.conf
    dest=/etc/nginx/nginx.conf
  notify: reload web server
  
- name: Deploy vhosts
  template: 
    src=vhost.conf
    dest={{ web_server__sites_dir }}/{{ item.name }}.conf
    owner=root group={{ common_web_user }} mode=0640
  with_items: web_server__vhosts
  notify: reload web server
