---
edx_portal__enabled: false
edx__lms_urlpath: "/edx"
edx__lms_port: "{{ EDXAPP_LMS_NGINX_PORT }}"
edx__cms_urlpath: "/edxcms"
edx__cms_port: "18010"
edx__xqueue_urlpath: "/xqueue"
edx__xqueue_port: "18040"
