---
- name: Install dnsmasq
  apt: 
    name={{item}}
    state=installed
  with_items:
    - dnsmasq
    - dnsutils

- name: Disable other dns servers
  service:
    name={{ item }}
    state=stopped
    enabled=false
  with_items:
    - bind9
  ignore_errors: true

- name: Deploy base config
  template:
    src=00-main.conf
    dest={{ dnsmasq__dir }}
    
- name: Enable dnsmasq
  service:
    name=dnsmasq
    state=started
    enabled=yes
  
  
