---
# TODO: Config dovecot and postix to only listen on localhost
- include: postfix.yml
- name: Install roundcube
  apt: >
    name={{item}}
    state=installed
  with_items:
    - roundcube
    - roundcube-plugins

# TODO: Ugly workaround for roundcube wanting to install Apache
- name: Apache should not be installed
  apt:
    name=apache2
    state=absent

- name: Configure roundcube
  lineinfile: "
    dest=/etc/roundcube/main.inc.php
    regex=^\$rcmail_config\['{{ item.setting }}
    line=$rcmail_config['{{ item.setting }}'] = {{ item.value }};"
  with_items:
    - setting: default_host
      value: 127.0.0.1
