---
dependencies:
  - role: web_server_vhosts
    web_server__vhosts:
      - name: "vidtest" 
        docroot: "{{ vidtest__docroot }}"
        extra:   
          nginx: "rewrite /rand[0-9]+(.*)$ /$1;"
