---
portal__enabled: false
portal__port: 80
portal__title: "x2go"
portal__subtitle: "Education in a box"
portal__description: |
  <p><strong>x2go</strong> is a collection of free learning materials hosted in a standalone box without requiring internet. </p>
  <p>It is developed by an international team, with representatives of <em>The Tunapanda Institute</em>, <em>The Queen Rania Foundation</em>, and <em>edX</em>. This portal page is based on work done by World Possible for Project RACHEL.
  </p>
  <p>As long as you are connected to the "x2go" wireless access point, you should be able to reach this page by going to
  <?php 
    if (isset($_SERVER['SERVER_ADDR'])) { 
      $a = $_SERVER['SERVER_ADDR'];
    } else {
      $a = print gethostbyname(gethostname()); 
    }
    print "<a href='http://$a'>$a</a>";
  ?>
  </p>
portal__base: "{{ provision__data_dir }}/portal"
portal__docroot: "{{ portal__base }}/site"
portal__site_content: "{{ portal__docroot }}"
portal__modules: "{{ portal__site_content }}/modules"
portal__redirects: "{{ portal__base }}/subsites.d"
portal__users: "{{ portal__base }}/authorized_clients"
portal__capture_chain: "captive"
# TODO figure out a way to get IP from ifupdown_external_interface
portal__redirect: "{{ ansible_wlan0 }}" 
portal__auth: "none"
portal__auth_agreement_text: |
  <div class="auth agreement">
  <p>By clicking this button, you agree to not be a jerk on the Internet.<br>
  In exchange, you'll be given access to the Internet (when it's available)!</p>
  <p>Even without Internet access, you can access any of the sites and resources linked below.<br />
  (please do not be a jerk on those sites either) </p>
  <p><strong>Happy learning!</strong></p>
  </div>
portal__auth_agreement_buttontext: "Ok, I won't be a jerk"
portal__auth_agreement_complete: |
  <div class="auth authorized">
  <p>You can use this portal to access the Internet if an Internet connection is available.<p>
  <p>Even if Internet access is not available, all of the content listed below is hosted locally and should be accessible!</p>
  <iframe src="http://duckduckgo.com/search.html?prefill=Internet Search" style="overflow:hidden;margin:0;padding:0;width:408px;height:40px;" frameborder="0"></iframe>
  <p><strong>Happy learning!</strong></p>
  </div>

