---
- name: Initiial timestamp
  hosts: all
  # TODO: Should this go elsewhere?
  handlers:
    - name: reload web server
      service: name=nginx state=reloaded

  tasks:
    - shell: echo "Last provisioning started at $(date)" > {{ provision__base_dir }}/provisioning.txt

- name: cubietruck ethernet setup
  hosts: cubietruck
  tasks:
    - name: Configure wlan driver
      lineinfile:
        dest=/etc/modules
        line="bcmdhd op_mode=2"
        regexp="^bcmdhd"
    
    - name: Load wlan driver
      command: modprobe bcmdhd
      ignore_errors: yes

- name: Base Setup
  hosts: all
  roles:
    - provision_base
