---
# TODO: This is an ugly hack. There's probably a better way.
- name: Changing default edx lms port
  lineinfile:
    dest=/edx/app/nginx/sites-available/lms 
    regexp='^(\s*)listen' 
    backrefs=yes 
    line='\1listen {{ EDXAPP_LMS_NGINX_PORT }} default;'
    state=present
