---
## Main Portal Pages ##
- name: Create portal directories
  file:
    path={{ item }}
    state=directory
    owner={{ provision__admin_user }} group={{ common_web_user }} mode=775 
    recurse=true
  with_items:
    - "{{ portal__docroot }}"

- name: Install portal host-specific landing page
  template:
    src=site/index.php
    dest={{ portal__docroot }}/index.php
    
- name: Symlink modules dir
  file:
    path={{ portal__docroot }}/modules
    src={{ portal__modules_dir }}
    state=link
  when: portal__modules_dir != "{{ portal__docroot }}/modules"

- name: Symlink sphider dir
  file:
    path={{ portal__docroot }}/rsphider
    src={{ sphider__root }}
    state=link
  when: >
    portal__use_sphider 
    and sphider__root != "{{ portal__docroot }}/rsphider"
       
- include: nginx.yml
  when: web_server__service=="nginx"

## Portal and Captive Auth Support Files ##
- include: captive.yml
  when: portal__auth is defined and portal__auth != "none"
  notify: reload iptables
