---
## Nginx Setup ##
- name: Remove existing default vhost
  file:
    path={{ web_server__conf_dir }}/default
    state=absent

- name: Deploy site config as default vhost
  template:
    src=nginx/portal.j2
    dest={{ web_server__sites_dir }}/portal.conf
    owner={{ provision__admin_user }} 
    group={{ common_web_user }} 
    mode=0640
  notify: reload web server

- name: Remove nginx default page
  file:
    path={{ provision__sites_enabled_dir }}/default
    state=absent
  notify: reload web server
