---
- name: Install Postfix
  apt: 
    name={{ item }}
    state=installed
  with_items:
    - postfix
    - dovecot-imapd
    #- dovecot-postfix

- name: Set postfix hostname
  lineinfile:
    dest=/etc/postfix/main.cf
    regexp=^myhostname
    line="myhostname = {{ provision__fqdn }}"

- name: Restart postfix
  service:
    name=postfix
    state=restarted
